export type CountryMeta = {
  capital: string;
  currency: string;
};

export const COUNTRY_META: Record<string, CountryMeta> = {
  Afghanistan: { capital: "Kabul", currency: "AFN" },
  Albania: { capital: "Tirana", currency: "ALL" },
  Algeria: { capital: "Algiers", currency: "DZD" },
  Andorra: { capital: "Andorra la Vella", currency: "EUR" },
  Angola: { capital: "Luanda", currency: "AOA" },
  "Antigua and Barbuda": { capital: "Saint John's", currency: "XCD" },
  Argentina: { capital: "Buenos Aires", currency: "ARS" },
  Armenia: { capital: "Yerevan", currency: "AMD" },
  Australia: { capital: "Canberra", currency: "AUD" },
  Austria: { capital: "Vienna", currency: "EUR" },
  Azerbaijan: { capital: "Baku", currency: "AZN" },
  Bahamas: { capital: "Nassau", currency: "BSD" },
  Bahrain: { capital: "Manama", currency: "BHD" },
  Bangladesh: { capital: "Dhaka", currency: "BDT" },
  Barbados: { capital: "Bridgetown", currency: "BBD" },
  Belarus: { capital: "Minsk", currency: "BYN" },
  Belgium: { capital: "Brussels", currency: "EUR" },
  Belize: { capital: "Belmopan", currency: "BZD" },
  Benin: { capital: "Porto-Novo", currency: "XOF" },
  Bhutan: { capital: "Thimphu", currency: "BTN" },
  Bolivia: { capital: "Sucre", currency: "BOB" },
  "Bosnia and Herzegovina": { capital: "Sarajevo", currency: "BAM" },
  Botswana: { capital: "Gaborone", currency: "BWP" },
  Brazil: { capital: "Brasília", currency: "BRL" },
  Brunei: { capital: "Bandar Seri Begawan", currency: "BND" },
  Bulgaria: { capital: "Sofia", currency: "BGN" },
  "Burkina Faso": { capital: "Ouagadougou", currency: "XOF" },
  Burundi: { capital: "Gitega", currency: "BIF" },
  "Cabo Verde": { capital: "Praia", currency: "CVE" },
  Cambodia: { capital: "Phnom Penh", currency: "KHR" },
  Cameroon: { capital: "Yaoundé", currency: "XAF" },
  Canada: { capital: "Ottawa", currency: "CAD" },
  "Central African Republic": { capital: "Bangui", currency: "XAF" },
  Chad: { capital: "N'Djamena", currency: "XAF" },
  Chile: { capital: "Santiago", currency: "CLP" },
  China: { capital: "Beijing", currency: "CNY" },
  Colombia: { capital: "Bogotá", currency: "COP" },
  Comoros: { capital: "Moroni", currency: "KMF" },
  "Congo (Republic of the)": { capital: "Brazzaville", currency: "XAF" },
  "Costa Rica": { capital: "San José", currency: "CRC" },
  "Côte d’Ivoire": { capital: "Yamoussoukro", currency: "XOF" },
  Croatia: { capital: "Zagreb", currency: "EUR" },
  Cuba: { capital: "Havana", currency: "CUP" },
  Cyprus: { capital: "Nicosia", currency: "EUR" },
  "Czech Republic": { capital: "Prague", currency: "CZK" },
  "Democratic Republic of the Congo": { capital: "Kinshasa", currency: "CDF" },
  Denmark: { capital: "Copenhagen", currency: "DKK" },
  Djibouti: { capital: "Djibouti", currency: "DJF" },
  Dominica: { capital: "Roseau", currency: "XCD" },
  "Dominican Republic": { capital: "Santo Domingo", currency: "DOP" },
  Ecuador: { capital: "Quito", currency: "USD" },
  Egypt: { capital: "Cairo", currency: "EGP" },
  "El Salvador": { capital: "San Salvador", currency: "USD" },
  "Equatorial Guinea": { capital: "Malabo", currency: "XAF" },
  Eritrea: { capital: "Asmara", currency: "ERN" },
  Estonia: { capital: "Tallinn", currency: "EUR" },
  Eswatini: { capital: "Mbabane / Lobamba", currency: "SZL" },
  Ethiopia: { capital: "Addis Ababa", currency: "ETB" },
  Fiji: { capital: "Suva", currency: "FJD" },
  Finland: { capital: "Helsinki", currency: "EUR" },
  France: { capital: "Paris", currency: "EUR" },
  Gabon: { capital: "Libreville", currency: "XAF" },
  Gambia: { capital: "Banjul", currency: "GMD" },
  Georgia: { capital: "Tbilisi", currency: "GEL" },
  Germany: { capital: "Berlin", currency: "EUR" },
  Ghana: { capital: "Accra", currency: "GHS" },
  Greece: { capital: "Athens", currency: "EUR" },
  Grenada: { capital: "St. George's", currency: "XCD" },
  Guatemala: { capital: "Guatemala City", currency: "GTQ" },
  Guinea: { capital: "Conakry", currency: "GNF" },
  "Guinea-Bissau": { capital: "Bissau", currency: "XOF" },
  Guyana: { capital: "Georgetown", currency: "GYD" },
  Haiti: { capital: "Port-au-Prince", currency: "HTG" },
  Honduras: { capital: "Tegucigalpa", currency: "HNL" },
  Hungary: { capital: "Budapest", currency: "HUF" },
  Iceland: { capital: "Reykjavík", currency: "ISK" },
  India: { capital: "New Delhi", currency: "INR" },
  Indonesia: { capital: "Jakarta", currency: "IDR" },
  Iran: { capital: "Tehran", currency: "IRR" },
  Iraq: { capital: "Baghdad", currency: "IQD" },
  Ireland: { capital: "Dublin", currency: "EUR" },
  Israel: { capital: "Jerusalem", currency: "ILS" },
  Italy: { capital: "Rome", currency: "EUR" },
  Jamaica: { capital: "Kingston", currency: "JMD" },
  Japan: { capital: "Tokyo", currency: "JPY" },
  Jordan: { capital: "Amman", currency: "JOD" },
  Kazakhstan: { capital: "Astana", currency: "KZT" },
  Kenya: { capital: "Nairobi", currency: "KES" },
  Kiribati: { capital: "South Tarawa", currency: "AUD" },
  Kuwait: { capital: "Kuwait City", currency: "KWD" },
  Kyrgyzstan: { capital: "Bishkek", currency: "KGS" },
  Laos: { capital: "Vientiane", currency: "LAK" },
  Latvia: { capital: "Riga", currency: "EUR" },
  Lebanon: { capital: "Beirut", currency: "LBP" },
  Lesotho: { capital: "Maseru", currency: "LSL" },
  Liberia: { capital: "Monrovia", currency: "LRD" },
  Libya: { capital: "Tripoli", currency: "LYD" },
  Liechtenstein: { capital: "Vaduz", currency: "CHF" },
  Lithuania: { capital: "Vilnius", currency: "EUR" },
  Luxembourg: { capital: "Luxembourg", currency: "EUR" },
  Madagascar: { capital: "Antananarivo", currency: "MGA" },
  Malawi: { capital: "Lilongwe", currency: "MWK" },
  Malaysia: { capital: "Kuala Lumpur", currency: "MYR" },
  Maldives: { capital: "Malé", currency: "MVR" },
  Mali: { capital: "Bamako", currency: "XOF" },
  Malta: { capital: "Valletta", currency: "EUR" },
  "Marshall Islands": { capital: "Majuro", currency: "USD" },
  Mauritania: { capital: "Nouakchott", currency: "MRU" },
  Mauritius: { capital: "Port Louis", currency: "MUR" },
  Mexico: { capital: "Mexico City", currency: "MXN" },
  Micronesia: { capital: "Palikir", currency: "USD" },
  Moldova: { capital: "Chișinău", currency: "MDL" },
  Monaco: { capital: "Monaco", currency: "EUR" },
  Mongolia: { capital: "Ulaanbaatar", currency: "MNT" },
  Montenegro: { capital: "Podgorica", currency: "EUR" },
  Morocco: { capital: "Rabat", currency: "MAD" },
  Mozambique: { capital: "Maputo", currency: "MZN" },
  Myanmar: { capital: "Naypyidaw", currency: "MMK" },
  Namibia: { capital: "Windhoek", currency: "NAD" },
  Nauru: { capital: "Yaren", currency: "AUD" },
  Nepal: { capital: "Kathmandu", currency: "NPR" },
  Netherlands: { capital: "Amsterdam", currency: "EUR" },
  "New Zealand": { capital: "Wellington", currency: "NZD" },
  Nicaragua: { capital: "Managua", currency: "NIO" },
  Niger: { capital: "Niamey", currency: "XOF" },
  Nigeria: { capital: "Abuja", currency: "NGN" },
  "North Korea": { capital: "Pyongyang", currency: "KPW" },
  "North Macedonia": { capital: "Skopje", currency: "MKD" },
  Norway: { capital: "Oslo", currency: "NOK" },
  Oman: { capital: "Muscat", currency: "OMR" },
  Pakistan: { capital: "Islamabad", currency: "PKR" },
  Palau: { capital: "Ngerulmud", currency: "USD" },
  Palestine: { capital: "East Jerusalem", currency: "ILS" },
  Panama: { capital: "Panama City", currency: "PAB" },
  "Papua New Guinea": { capital: "Port Moresby", currency: "PGK" },
  Paraguay: { capital: "Asunción", currency: "PYG" },
  Peru: { capital: "Lima", currency: "PEN" },
  Philippines: { capital: "Manila", currency: "PHP" },
  Poland: { capital: "Warsaw", currency: "PLN" },
  Portugal: { capital: "Lisbon", currency: "EUR" },
  Qatar: { capital: "Doha", currency: "QAR" },
  Romania: { capital: "Bucharest", currency: "RON" },
  Russia: { capital: "Moscow", currency: "RUB" },
  Rwanda: { capital: "Kigali", currency: "RWF" },
  "Saint Kitts and Nevis": { capital: "Basseterre", currency: "XCD" },
  "Saint Lucia": { capital: "Castries", currency: "XCD" },
  "Saint Vincent and the Grenadines": { capital: "Kingstown", currency: "XCD" },
  Samoa: { capital: "Apia", currency: "WST" },
  "San Marino": { capital: "City of San Marino", currency: "EUR" },
  "São Tomé and Príncipe": { capital: "São Tomé", currency: "STN" },
  "Saudi Arabia": { capital: "Riyadh", currency: "SAR" },
  Senegal: { capital: "Dakar", currency: "XOF" },
  Serbia: { capital: "Belgrade", currency: "RSD" },
  Seychelles: { capital: "Victoria", currency: "SCR" },
  "Sierra Leone": { capital: "Freetown", currency: "SLE" },
  Singapore: { capital: "Singapore", currency: "SGD" },
  Slovakia: { capital: "Bratislava", currency: "EUR" },
  Slovenia: { capital: "Ljubljana", currency: "EUR" },
  "Solomon Islands": { capital: "Honiara", currency: "SBD" },
  Somalia: { capital: "Mogadishu", currency: "SOS" },
  "South Africa": { capital: "Pretoria", currency: "ZAR" },
  "South Korea": { capital: "Seoul", currency: "KRW" },
  "South Sudan": { capital: "Juba", currency: "SSP" },
  Spain: { capital: "Madrid", currency: "EUR" },
  "Sri Lanka": { capital: "Sri Jayawardenepura Kotte", currency: "LKR" },
  Sudan: { capital: "Khartoum", currency: "SDG" },
  Suriname: { capital: "Paramaribo", currency: "SRD" },
  Sweden: { capital: "Stockholm", currency: "SEK" },
  Switzerland: { capital: "Bern", currency: "CHF" },
  Syria: { capital: "Damascus", currency: "SYP" },
  Tajikistan: { capital: "Dushanbe", currency: "TJS" },
  Tanzania: { capital: "Dodoma", currency: "TZS" },
  Thailand: { capital: "Bangkok", currency: "THB" },
  "Timor-Leste": { capital: "Dili", currency: "USD" },
  Togo: { capital: "Lomé", currency: "XOF" },
  Tonga: { capital: "Nuku'alofa", currency: "TOP" },
  "Trinidad and Tobago": { capital: "Port of Spain", currency: "TTD" },
  Tunisia: { capital: "Tunis", currency: "TND" },
  Turkey: { capital: "Ankara", currency: "TRY" },
  Turkmenistan: { capital: "Ashgabat", currency: "TMT" },
  Tuvalu: { capital: "Funafuti", currency: "AUD" },
  Uganda: { capital: "Kampala", currency: "UGX" },
  Ukraine: { capital: "Kyiv", currency: "UAH" },
  "United Arab Emirates": { capital: "Abu Dhabi", currency: "AED" },
  "United Kingdom": { capital: "London", currency: "GBP" },
  "United States": { capital: "Washington, D.C.", currency: "USD" },
  Uruguay: { capital: "Montevideo", currency: "UYU" },
  Uzbekistan: { capital: "Tashkent", currency: "UZS" },
  Vanuatu: { capital: "Port Vila", currency: "VUV" },
  "Vatican City": { capital: "Vatican City", currency: "EUR" },
  Venezuela: { capital: "Caracas", currency: "VES" },
  Vietnam: { capital: "Hanoi", currency: "VND" },
  Yemen: { capital: "Sana'a", currency: "YER" },
  Zambia: { capital: "Lusaka", currency: "ZMW" },
  Zimbabwe: { capital: "Harare", currency: "USD" },
};

export const getCountryMeta = (countryName: string): CountryMeta | null =>
  COUNTRY_META[countryName] ?? null;

